apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: qdrouterds.interconnectedcloud.github.io
spec:
  group: interconnectedcloud.github.io
  names:
    kind: Qdrouterd
    listKind: QdrouterdList
    plural: qdrouterds
    singular: qdrouterd
    shortNames:
    - qdr
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      required:
        - spec
      properties:
        spec:
          properties:
            count:
              type: integer
              minimum: 1
              maximum: 10
            deploymentMode:
              type: string
              enum:
                - lbfrontend
                - daemonset
              description: The deployment mode
            image:
              type: string
              description: The image used for the qdrouerd deployment
            listeners:
              type: array
              description: Configuration of each individual qdrouterd listener
              minItems: 1
              items:
                type: object
                description: qdrouterd listener configuration
                properties:
                  name:
                    type: string
                    description: Listener name
                  host:
                    type: string
                    description: Host name
                  port:
                    type: integer
                    description: Port number
                  routeContainer:
                    type: boolean
                    description: Indicator for a router-broker connection
                  http:
                    type: boolean
                    description: Accept HTTP connections
                  cost:
                    type: integer
                    description: Cost metric for inter router connections
                  sslProfile:
                    type: string
                    description: Name of the ssl profile to use
            interRouterListeners:
              type: array
              description: Configuration of each individual inter router listener
              minItems: 1
              items:
                type: object
                description: qdrouterd listener configuration
                properties:
                  name:
                    type: string
                    description: Listener name
                  host:
                    type: string
                    description: Host name
                  port:
                    type: integer
                    description: Port number
                  routeContainer:
                    type: boolean
                    description: Indicator for a router-broker connection
                  http:
                    type: boolean
                    description: Accept HTTP connections
                  cost:
                    type: integer
                    description: Cost metric for inter router connections
                  sslProfile:
                    type: string
                    description: Name of the ssl profile to use
            addresses:
              type: array
              description: Configuration of each address distribution and phasing
              items:
                type: object
                description: address configuration
                properties:
                  prefix:
                    type: string
                    description: The address prefix for the configured setting
                  pattern:
                    type: string
                    description: A wildcarded pattern for address matching
                  distribution:
                    type: string
                    description: Treatment of traffic associated with the address
                    enum:
                      - balanced
                      - closest
                      - multicast
                  waypoint:
                    type: boolean
                    description: Indicator for waypoint use
                  ingressPhase:
                    type: integer
                    minimum: 0
                    maximum: 9
                    description: Ingress phase override for the address
                  egressPhase:
                    type: integer
                    minimum: 0
                    maximum: 9
                    description: Egress phase override for the address
                  priority:
                    type: integer
                    minimum: 0
                    maximum: 9
                    description: Priority assigned to address for inter router transfer
